name: Deploy

on:
  push:
    branches:
      - main

permissions: 
  id-token: write
  pages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: 
      group: build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci

      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@main
